### ISSUE TITLE
"Could not find stored procedure 'GO'." error for script starting with GO

### ISSUE THREAD

**Issue by dahlbyk** [chucknorris/roundhouse#202]
While converting from Tarantino I got stuck for a bit with this error because a script started with `GO`. I'm also able to reproduce with a script that contains only `GO`.

**Comment by ferventcoder** [comment]
I'm going with a known issue. Most of the time rh does the right thing - in some cases you need an empty line (or a space) before GO.

**Comment by ferventcoder** [comment]
With Oracle we are very explicit in how batch splitting works - https://github.com/chucknorris/roundhouse/wiki/Oracle

**Comment by ferventcoder** [comment]
Would you consider a GO as first line a valid use case?

**Comment by dahlbyk** [comment]
I don't know of a *good* reason to start a script with `GO`, but we had one that caused unexpected behavior so...maybe?

For the record this is against SQL Server. Any particulars about how its batch splitting works? I'm also seeing some weirdness in a large set of test data inserts that have `GO`s placed every few hundred lines to make smaller batches.

**Comment by ferventcoder** [comment]
You will have the least amount of problems if the GO is on it's own line. And don't put it first. Ask a DBA if that is a valid use case. I can say RH doesn't really support empty Gos but I thought we fixed that in a more recent release - what version are you seeing this on?

**Comment by dahlbyk** [comment]
RH 0.8.5.0

The empty `GO` issue was resolved by deleting it, so maybe having this issue Google-able is a sufficient fix if one within RH isn't trivial.

For the other `GO` weirdness, the file structure is...

```sql
SET IDENTITY_INSERT [dbo].[Foo] ON
INSERT [dbo].[Foo] ...
INSERT [dbo].[Foo] ...
INSERT [dbo].[Foo] ...
...
GO
INSERT [dbo].[Foo] ...
INSERT [dbo].[Foo] ...
INSERT [dbo].[Foo] ...
...
SET IDENTITY_INSERT [dbo].[Foo] OFF
```

I tried adding an `IDENTITY_INSERT` `OFF`/`ON` pair surrounding each `GO` with no impact. The file runs without issue in SSMS and Tarantino, so I assume it's weirdness with the RH batch splitting.

**Comment by ferventcoder** [comment]
I'm almost sure that we've fixed this in 0.8.6

**Comment by ferventcoder** [comment]
Perhaps take it for a test drive?

**Comment by ferventcoder** [comment]
Here's where we simplified the regex - https://github.com/chucknorris/roundhouse/pull/100/files

**Comment by ferventcoder** [comment]
https://github.com/chucknorris/roundhouse/blob/master/README.markdown

**Comment by dahlbyk** [comment]
0.8.6 does give a better error message:

```
Error executing file 'test.sql': statement running was 'GO
'
RoundhousE encountered an error.
System.Data.SqlClient.SqlException: Could not find stored procedure 'GO'.
   at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection)
   at System.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection)
   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj)
   at System.Data.SqlClient.TdsParser.Run(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj)
   at System.Data.SqlClient.SqlCommand.RunExecuteNonQueryTds(String methodName, Boolean async)
   at System.Data.SqlClient.SqlCommand.InternalExecuteNonQuery(DbAsyncResult result, String methodName, Boolean sendToPipe)
   at System.Data.SqlClient.SqlCommand.ExecuteNonQuery()
   at roundhouse.databases.AdoNetDatabase.run_command_with(String sql_to_run, ConnectionType connection_type, IList`1 parameters)
```

The upgrade also doesn't fix the bulk insert weirdness, and including the (very very large) statement running actually makes it harder to troubleshoot... may be wise to chop the middle out of very large error statements?

**Comment by ferventcoder** [comment]
I think that adding `-debug` may even make very large statements worse.

**Comment by ferventcoder** [comment]
I don't recall if there is a way to remove the statements. Making it shorter def might help.

**Comment by ferventcoder** [comment]
@ChrisMissal can you triage this for a release?

**Comment by ChrisMissal** [comment]
@ferventcoder yup, I'm checking it out now

@dahlbyk can you share the contents of `test.sql` please? I can reproduce this in some cases, but not others.

**Comment by dahlbyk** [comment]
`test.sql` is just `GO\r\n`, targetting SQL Server (2012 Express, though I doubt that matters).

**Comment by ChrisMissal** [comment]
@dahlbyk @ferventcoder I don't know enough about this area to give great feedback, but there are three different regexes based on DatabaseType (which is why I asked). I'd like to keep this open, but I don't necessary want to mark it for the next release.
